### ISSUE TITLE
Change repo name to openSIMP

### ISSUE THREAD

**Issue by KasraIDK** [Spixa/Suschat#1]
why has it not changed yet

**Comment by vivyir** [comment]
sussy baka

**Comment by KasraIDK** [comment]
aewouga imposter :flushed:

**Comment by Spixa** [comment]
hold your nose

**Comment by vivyir** [comment]
> hold your nose

:flushed:

**Comment by KasraIDK** [comment]
> hold your nose

Dont delete my comment that was rude :angry:

**Comment by Spixa** [comment]
> > hold your nose
> 
> Dont delete my comment that was rude :angry:

no

**Comment by Spixa** [comment]
guys shut up

**Comment by phnixir** [comment]
> guus shut up

`guus` :flushed:

**Comment by vivyir** [comment]
we have reached, the telos
