### ISSUE TITLE
strip newlines from broadcasting

### ISSUE THREAD

**Issue by vivyir** [Spixa/Suschat#4]
the openSIMP server accepts and broadcasts newlines if they're mixed in with normal text (testable with the susrust utility), proposed solution is to strip them before re-broadcasting since the messages themselves may contain valid data

**Comment by Spixa** [comment]
ok

**Comment by Spixa** [comment]
ill fix it one day

**Comment by Spixa** [comment]
and its only 1 line of code but i dont feel like it
